export const TOKEN = {
    DB: Symbol('DB'),
    REDIS: Symbol('REDIS'),
    LOGGER: Symbol('LOGGER'),
    ERROR_CONTROLLER: Symbol('ERROR_CONTROLLER'),
    DOMAIN_EVENT_BUS: Symbol('DOMAIN_EVENT_BUS'),
    COMMAND_EVENT_BUS: Symbol('COMMAND_EVENT_BUS'),
    QUERY_EVENT_BUS: Symbol('QUERY_EVENT_BUS'),
    WORKER_USER: Symbol('WORKER_USER'),
    WORKER_VIDEO: Symbol('WORKER_VIDEO'),
    SNS_CLIENT: Symbol('SNS_CLIENT'),
    SQS_CLIENT: Symbol('SQS_CLIENT'),
};
