export const USER_TOKEN = {
    // Storage
    DB_MODEL: Symbol('USER_DB_MODEL'),

    // SNS
    SNS_TOPIC_ARN: Symbol('SNS_USER_TOPIC_ARN'),
    SNS_EVENT_PUBLISHER: Symbol('SNS_USER_EVENT_PUBLISHER'),

    // Consumers

    // Handlers
    CREATE_VIDEO_READ_HANDLER: Symbol('CREATE_VIDEO_READ_HANDLER'),
    CREATE_USER_HANDLER: Symbol('CREATE_USER_HANDLER'),

    // SQS
    SQS_USER_CREATED_QUEUE_URL: Symbol('SQS_USER_CREATED_QUEUE_URL'),

    // Controllers
    CREATE_USER_CONTROLLER: Symbol('CREATE_USER_CONTROLLER'),

    // Use Cases
    INCREASE_AMOUNT_OF_VIDEOS_USE_CASE: Symbol('INCREASE_AMOUNT_OF_VIDEOS_USE_CASE'),
    CREATE_USER_USE_CASE: Symbol('CREATE_USER_USE_CASE'),

    // Repositories
    REPOSITORY: Symbol('USER_REPOSITORY'),
};
