export const TOKEN = {
    // Storage
    DB_MODEL: Symbol('USER_DB_MODEL'),
    REPOSITORY: Symbol('USER_REPOSITORY'),

    // AWS
    SNS_TOPIC_ARN: Symbol('SNS_USER_TOPIC_ARN'),
    SNS_EVENT_PUBLISHER: Symbol('SNS_USER_EVENT_PUBLISHER'),

    SQS_USER_CREATED_QUEUE_URL: Symbol('SQS_USER_CREATED_QUEUE_URL'),
    SQS_EVENT_PUBLISHED_CONSUMER: Symbol('SQS_USER_EVENT_PUBLISHED_CONSUMER'),

    // Application
    INCREASE_AMOUNT_OF_VIDEOS_ON_VIDEO_PUBLISHED_HANDLER: Symbol(
        'INCREASE_AMOUNT_OF_VIDEOS_ON_VIDEO_PUBLISHED_HANDLER'
    ),
    INCREASE_AMOUNT_OF_VIDEOS_USE_CASE: Symbol('INCREASE_AMOUNT_OF_VIDEOS_USE_CASE'),
    CREATE_USER_CONTROLLER: Symbol('CREATE_USER_CONTROLLER'),
    CREATE_USER_USE_CASE: Symbol('CREATE_USER_USE_CASE'),
};
