export const TOKEN = {
    // Storage
    DB_MODEL: Symbol('VIDEO_DB_MODEL'),
    REPOSITORY: Symbol('VIDEO_REPOSITORY'),

    // AWS
    SNS_TOPIC_ARN: Symbol('SNS_VIDEO_TOPIC_ARN'),
    SNS_EVENT_PUBLISHER: Symbol('SNS_VIDEO_EVENT_PUBLISHER'),

    SQS_EVENT_PUBLISHED_CONSUMER: Symbol('SQS_VIDEO_EVENT_PUBLISHED_CONSUMER'),
    SQS_VIDEO_PUBLISHED_QUEUE_URL: Symbol('SQS_VIDEO_PUBLISHED_QUEUE_URL'),

    // Application
    PUBLISH_VIDEO_CONTROLLER: Symbol('PUBLISH_VIDEO_CONTROLLER'),
    PUBLISH_VIDEO_USE_CASE: Symbol('PUBLISH_VIDEO_USE_CASE'),
    GET_VIDEOS_CONTROLLER: Symbol('GET_VIDEOS_CONTROLLER'),
    GET_VIDEOS_USE_CASE: Symbol('GET_VIDEOS_USE_CASE'),
};
