export const TOKEN = {
    CREATE_VIDEO_CONTROLLER: Symbol('CREATE_VIDEO_CONTROLLER'),
    CREATE_VIDEO_USE_CASE: Symbol('CREATE_VIDEO_USE_CASE'),
    VIDEO_REPOSITORY: Symbol('VIDEO_REPOSITORY'),
    DB_VIDEO: Symbol('DB_VIDEO'),
};
