export const TOKEN = {
    // Storage
    DB_MODEL_COMMENT: Symbol('VIDEO_COMMENT_DB_MODEL'),

    // Application
    ADD_COMMENT_TO_VIDEO_USE_CASE: Symbol('ADD_COMMENT_TO_VIDEO_USE_CASE'),
    ADD_COMMENT_TO_VIDEO_CONTROLLER: Symbol('ADD_COMMENT_TO_VIDEO_CONTROLLER'),
};
