export const VIDEO_COMMENT_TOKENS = {
    // Storage
    DB_MODEL: Symbol('VIDEO_COMMENT_DB_MODEL'),

    // Controllers
    ADD_COMMENT_TO_VIDEO_CONTROLLER: Symbol('ADD_COMMENT_TO_VIDEO_CONTROLLER'),

    // Use Cases
    ADD_COMMENT_TO_VIDEO_USE_CASE: Symbol('ADD_COMMENT_TO_VIDEO_USE_CASE'),
};
