export const TOKEN = {
    CREATE_VIDEO_CONTROLLER: Symbol('CREATE_VIDEO_CONTROLLER'),
    CREATE_VIDEO_USE_CASE: Symbol('CREATE_VIDEO_USE_CASE'),
    VIDEO_REPOSITORY: Symbol('VIDEO_REPOSITORY'),
    DB_VIDEO: Symbol('DB_VIDEO'),
    EVENT_BUS: Symbol('EVENT_BUS'),
    SNS_EVENT_PUBLISHER: Symbol('SNS_EVENT_PUBLISHER'),
    SNS_CLIENT: Symbol('SNS_CLIENT'),
    ERROR_CONTROLLER: Symbol('ERROR_CONTROLLER'),
    LOGGER: Symbol('LOGGER'),
};
