export const VIDEO_TOKEN = {
    // Storage
    DB_MODEL: Symbol('VIDEO_DB_MODEL'),
    VIDEO_PROJECTION_DB_MODEL: Symbol('VIDEO_VIDEO_PROJECTION_DB_MODEL'),
    REDIS: Symbol('REDIS'),

    // AWS
    SNS_TOPIC_ARN: Symbol('SNS_VIDEO_TOPIC_ARN'),

    // Repositories
    REPOSITORY: Symbol('VIDEO_REPOSITORY'),
    VIDEO_COMMENT_REPOSITORY: Symbol('VIDEO_COMMENT_REPOSITORY'),
    DB_REPOSITORY: Symbol('VIDEO_DB_REPOSITORY'),
    VIDEO_PROJECTION_REPOSITORY: Symbol('VIDEO_PROJECTION_REPOSITORY'),
    GET_VIDEOS_REPOSITORY: Symbol('GET_VIDEOS_REPOSITORY'),
};
