export const VIDEO_TOKEN = {
    // Storage
    DB_MODEL: Symbol('VIDEO_DB_MODEL'),
    VIDEO_PROJECTION_DB_MODEL: Symbol('VIDEO_VIDEO_PROJECTION_DB_MODEL'),
    REDIS: Symbol('REDIS'),

    // SNS
    SNS_TOPIC_ARN: Symbol('SNS_VIDEO_TOPIC_ARN'),
    SNS_EVENT_PRODUCER: Symbol('SNS_VIDEO_EVENT_PRODUCER'),
    IN_MEMORY_EVENT_PUBLISHER: Symbol('IN_MEMORY_VIDEO_EVENT_PUBLISHER'),

    // Consumers
    IN_MEMORY_EVENT_VIDEO_CREATED_SUBSCRIBER: Symbol('IN_MEMORY_EVENT_VIDEO_CREATED_SUBSCRIBER'),
    IN_MEMORY_EVENT_COMMENT_ADDED_SUBSCRIBER: Symbol('IN_MEMORY_EVENT_COMMENT_ADDED_SUBSCRIBER'),

    FAILOVER_DOMAIN_EVENTS: Symbol('FAILOVER_DOMAIN_EVENTS'),

    // CQRS Handlers
    CREATE_VIDEO_COMMAND_HANDLER: Symbol('CREATE_VIDEO_COMMAND_HANDLER'),
    GET_VIDEOS_QUERY_HANDLER: Symbol('GET_VIDEOS_QUERY_HANDLER'),

    // Domain Handlers
    CREATE_PROJECTION_HANDLER: Symbol('CREATE_PROJECTION_HANDLER'),
    INCREASE_AMOUNT_OF_COMMENTS_HANDLER: Symbol('INCREASE_AMOUNT_OF_COMMENTS_HANDLER'),

    // Controllers
    PUBLISH_VIDEO_CONTROLLER: Symbol('PUBLISH_VIDEO_CONTROLLER'),
    GET_VIDEOS_CONTROLLER: Symbol('GET_VIDEOS_CONTROLLER'),

    // Use Cases
    PUBLISH_VIDEO_USE_CASE: Symbol('PUBLISH_VIDEO_USE_CASE'),
    GET_VIDEOS_USE_CASE: Symbol('GET_VIDEOS_USE_CASE'),
    CREATE_PROJECTION_USE_CASE: Symbol('CREATE_PROJECTION_USE_CASE'),
    INCREASE_AMOUNT_OF_COMMENTS_USE_CASE: Symbol('INCREASE_AMOUNT_OF_COMMENTS_USE_CASE'),

    // Repositories
    REPOSITORY: Symbol('VIDEO_REPOSITORY'),
    VIDEO_COMMENT_REPOSITORY: Symbol('VIDEO_COMMENT_REPOSITORY'),
    DB_REPOSITORY: Symbol('VIDEO_DB_REPOSITORY'),
    VIDEO_PROJECTION_REPOSITORY: Symbol('VIDEO_PROJECTION_REPOSITORY'),
    GET_VIDEOS_REPOSITORY: Symbol('GET_VIDEOS_REPOSITORY'),
};
