export const USER_TOKEN = {
    // Storage
    DB_MODEL: Symbol('USER_DB_MODEL'),

    // Event Bridge
    EVENT_BRIDGE_USER_TOPIC_ARN: Symbol('EVENT_BRIDGE_USER_TOPIC_ARN'),
    EVENT_BRIDGE_EVENT_PRODUCER: Symbol('EVENT_BRIDGE_USER_EVENT_PRODUCER'),

    // Consumers
    SQS_EVENT_USER_CREATED_CONSUMER: Symbol('SQS_EVENT_USER_CREATED_CONSUMER'),
    SQS_EVENT_VIDEO_CREATED_CONSUMER: Symbol('SQS_EVENT_VIDEO_CREATED_CONSUMER'),

    // Handlers
    CREATE_USER_HANDLER: Symbol('CREATE_USER_HANDLER'),
    INCREASE_AMOUNT_OF_VIDEOS_HANDLER: Symbol('INCREASE_AMOUNT_OF_VIDEOS_HANDLER'),
    USER_CREATED_HANDLER: Symbol('USER_CREATED_HANDLER'),
    // SQS
    SQS_USER_CREATED_QUEUE_URL: Symbol('SQS_USER_CREATED_QUEUE_URL'),
    SQS_VIDEO_CREATED_QUEUE_URL: Symbol('SQS_VIDEO_CREATED_QUEUE_URL'),

    // Controllers
    CREATE_USER_CONTROLLER: Symbol('CREATE_USER_CONTROLLER'),

    // Use Cases
    INCREASE_AMOUNT_OF_VIDEOS_USE_CASE: Symbol('INCREASE_AMOUNT_OF_VIDEOS_USE_CASE'),
    CREATE_USER_USE_CASE: Symbol('CREATE_USER_USE_CASE'),

    // Repositories
    REPOSITORY: Symbol('USER_REPOSITORY'),
};
