export const USER_TOKEN = {
    // Storage
    DB_MODEL: Symbol('USER_DB_MODEL'),

    // SNS
    SNS_TOPIC_ARN: Symbol('SNS_USER_TOPIC_ARN'),
    SNS_EVENT_PRODUCER: Symbol('SNS_USER_EVENT_PRODUCER'),

    // Consumers
    SQS_EVENT_USER_CREATED_CONSUMER: Symbol('SQS_EVENT_USER_CREATED_CONSUMER'),

    // Handlers
    CREATE_USER_HANDLER: Symbol('CREATE_USER_HANDLER'),
    INCREASE_AMOUNT_OF_VIDEOS_HANDLER: Symbol('INCREASE_AMOUNT_OF_VIDEOS_HANDLER'),

    // SQS
    SQS_USER_CREATED_QUEUE_URL: Symbol('SQS_USER_CREATED_QUEUE_URL'),

    // Controllers
    CREATE_USER_CONTROLLER: Symbol('CREATE_USER_CONTROLLER'),

    // Use Cases
    INCREASE_AMOUNT_OF_VIDEOS_USE_CASE: Symbol('INCREASE_AMOUNT_OF_VIDEOS_USE_CASE'),
    CREATE_USER_USE_CASE: Symbol('CREATE_USER_USE_CASE'),

    // Repositories
    REPOSITORY: Symbol('USER_REPOSITORY'),
};
