export const USER_TOKEN = {
    // AWS
    SQS_USER_CREATED_QUEUE_URL: Symbol('SQS_USER_CREATED_QUEUE_URL'),
    SQS_VIDEO_CREATED_QUEUE_URL: Symbol('SQS_VIDEO_CREATED_QUEUE_URL'),
    EVENT_BRIDGE_USER_TOPIC_ARN: Symbol('EVENT_BRIDGE_USER_TOPIC_ARN'),

    // Repositories
    REPOSITORY: Symbol('USER_REPOSITORY'),
};
